[Backport fourth] Update README.md
ewanharris/test-backport pull request #49
Opened 2020-09-03 20:23 UTC by ewanharris

Backport of #48.
See that PR for full details.

2020-10-20 15:41 UTC, alasdairhurst requested changes

2020-10-20 15:41 UTC, alasdairhurst commented on README.md
> +test 23
23 is outdated, should be 24 now.

2020-10-20 15:42 UTC, alasdairhurst commented
Please fix

2020-10-20 21:16 UTC, ewanharris commented
@alasdairhurst please fork the project if you need this fix earlier

2020-10-21 13:53 UTC, alasdairhurst commented
Sorry,  we need this particular repository otherwise our process breaks. It's not possible to use a fork

2021-02-09 20:25 UTC, closed without merging